baseURL: https://MishimaLIKO.github.io/
title: LIKO＼李璐
theme: mini
pagination:
  pagerSize: 10

# 介面語言設為英文，以對應英文翻譯
languageCode: en-us
hasCJKLanguage: true
googleAnalytics: G-GMSTCBCHEG

markup:
  highlight:
    guessSyntax: true
    style: emacs

outputs:
  home:
    - HTML
    - RSS
    - JSON

# 社交連結
social:
  github: https://github.com/MishimaLIKO
  twitter: https://twitter.com/MishimaLIKO

params:
  author: liko
  bio: Novelist
  description: Liko's Blog
  enableComments: true
  enableGoogleAnalytics: true
  
  # 導覽列連結（英文）
  links:
    - name: About
      path: /about
    - name: Search
      path: /search
