
# baseURL: https://nodejh.github.io/hugo-theme-mini
baseURL: https://MishimaLIKO.github.io/
languageCode: zh-tw
title: LIKO＼李璐
theme: mini
pagination:
  pagerSize: 10

hasCJKLanguage: true
permalinks:
  posts: /posts/:title/

googleAnalytics: G-GMSTCBCHEG
#disqusShortname: https-mishimaliko-github-io


markup:
  highlight:
    guessSyntax: true
    style: emacs


# social:
  # github: https://github.com/nodejh
  # twitter: https://twitter.com/nodejh
  # stackoverflow: https://stackoverflow.com/users/4518882/nodejh

social:
  github: https://github.com/MishimaLIKO
  twitter: https://twitter.com/MishimaLIKO

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  author: liko
  bio: Novelist
  description: Liko's Blog
  # enableRSS: true
  enableComments: true
  enableGoogleAnalytics: true

  links:
    - name: Search
      path: /search


